### ISSUE TITLE
Feature request: Chat window callbacks

### ISSUE THREAD

**Issue by jschr** [bluejeans/sdk-webrtc-meetings#11]
Would be nice to be able to hook into BJN's chat window and create / show messages using the webtrc sdk.

**Comment by glenninn** [comment]
Jordan
  If you look at the bjn dev site. There is a reference design for connecting into chat

https://github.com/bluejeans/sdk-chat-meetings

Glenn
Sent from my iPhone 
May also include voice transcribed
(please excuse any typos)

**Comment by jschr** [comment]
Oh great, thanks Glenn!
