### ISSUE TITLE
Connection errors

### ISSUE THREAD

**Issue by init-tpetrovic** [bluejeans/sdk-webrtc-meetings#5]
Hi

We have started getting errors from WebRTC client, also present in the reference application. Can you please check it out?

![image](https://user-images.githubusercontent.com/6770406/52952191-23c01000-3384-11e9-9e18-df799ab945de.png)

**Comment by glenninn** [comment]
Hi Tomislav,
  We have updated the peer connection code to correctly handle this change from Chrome (build 72).  Google is expecting, by default, to use the Unified Plan for SDP, and currently BlueJeans cloud is in implementation of this.  So we need to configure Chrome to use "plan-b" for SDP.
